### ISSUE TITLE
Can't connect to sftp server

### ISSUE THREAD

**Issue by YairHadari** [sveale/remote-edit#60]
Hi,

Thanks for contributing the package!!!
unfortunately, I can't connect to any sftp server thank I"m connecting with Putty.

I"m getting the following error:
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 timeCreate Issue on remote-edit repo
Atom.Object.defineProperty.get - /opt/atom/resources/app/src/atom.js:54:11
OpenFilesView.attach - /home/yair/.atom/packages/remote-edit/lib/view/open-files-view.coffee:19:11

Please advice,
Yair

**Comment by sveale** [comment]
This is likely due to usage of Atom's old API. I've just pushed a new version of the package that should fix the issue.

**Comment by YairHadari** [comment]
Thanks Sveale!

unfortunately I"m still getting timeout message when trying to connect to the server
