### ISSUE TITLE
Add new host form doesn't accept input

### ISSUE THREAD

**Issue by pkese** [sveale/remote-edit#61]
I've just installed fresh release of atom.io and remote-edit.

When I go to the 'Add new host' dialog (both ftp and sftp), I can select input field, but when typing in, the keystrokes don't appear in the input field -- nothing happens. There isn't any cursor either.
There's no errors in the console either.

Am I doing something wrong (I'm an Atom newbie).

![atom](https://cloud.githubusercontent.com/assets/278492/6413732/9fea9e86-be92-11e4-9fdf-f0c0c5999f9b.png)

**Comment by pkese** [comment]
I've even tried to go through the deprecations-cop reports and fixed all the issues in the source code, but the input fields still don't work.

**Comment by sveale** [comment]
Hi! The master branch already contains fixes to the issues you're having, but due to quite large updates in atom's api and accompanying packages there is still some broken functionality that hasn't been fixed in remote-edit, and as such I haven't been able to push a new version of the package. I'll probably get it fixed soon :-) 

---- Peter Keše skrev ----

**Comment by sveale** [comment]
In the meantime, you could try one of the other packages that offer similar functionality. Just search for sftp

**Comment by 190n** [comment]
I can use the input fields on Ubuntu 14.10.
I'm using Atom v0.181.0, remote-edit v1.6.4.

**Comment by Rympau** [comment]
Got the same problem on Windows 7 x64, Atom v.0.184.0, remote-edit v.1.6.4
I've tried to maunally replace package with downloaded from GitHub but in this case dialogs don't even show up.

**Comment by sveale** [comment]
I've just pushed version 1.7.0 of the package to atom. Should resolve the issue.
Would be great if you could try it out, and let me know if it resolves the issue.

**Comment by Rympau** [comment]
It works! Issue resolved.

**Comment by polsab** [comment]
Still not working for me. The fields are highlighted now when selected, but the keystrokes still don't appear. I'm on OSX 10.10.2, Atom 0.184.0.

**Comment by pkese** [comment]
@sveale Version 1.7.0 indeed works. Thanks for your help :)

**Comment by FriscoTony** [comment]
I can also confirm that non-editable fields are fixed for me as well with 1.7.0. Thanks!

**Comment by sveale** [comment]
Great to hear :)
@polsab I'm using the same version of OSX as you, but Atom 0.186.0. Are you getting any errors in the console or otherwise?

**Comment by polsab** [comment]
@sveale Just updated to 0.186.0 and the problem is gone. Thanks!
